version: '3.4'

services:

  movies.api:
    image: ${DOCKER_REGISTRY-}moviesapi
    container_name: Movies.Api
    build:
      context: .
      dockerfile: Movies.API/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"

  movies.reporting.api:
    image: ${DOCKER_REGISTRY-}moviesreportingapi
    container_name: Movies.Reporting.Api
    build:
      context: .
      dockerfile: Movies.Reporting.API/Dockerfile
    ports:
      - "6000:80"
      - "6001:443"


  movies.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Movies.Db
    volumes:
        - ./.containers/database:/var/opt/mssql/data
    ports:
        - "1433:1433"
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Strong_password_123!"

  movies.mq:
    image: rabbitmq:management
    container_name: Movies.RabbitMq
    hostname: movies-mq
    volumes:
        - ./.containers/queue/data/:/var/lib/rabbitmq
        - ./.containers/queue/log/:/var/log/rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
